# Generated by Django 2.0.7 on 2018-09-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
