# Generated by Django 2.0.7 on 2018-09-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usuarios_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
