# Generated by Django 2.0.7 on 2018-09-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_professor_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='descricaoDisciplina',
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.CharField(max_length=12),
        ),
    ]
