# Generated by Django 2.0.7 on 2018-09-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20180915_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='descricaoDesempenho',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='frequencia',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='professor',
            field=models.ManyToManyField(blank=True, to='cadastros.Professor'),
        ),
    ]
