# Generated by Django 2.0.7 on 2018-09-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpf',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Cpf',
        ),
    ]
