# Generated by Django 2.0.7 on 2018-09-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20180917_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesProfessor',
            fields=[
                ('titulo', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Perguntasx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=100)),
                ('alternativa_a', models.CharField(max_length=200)),
                ('alternativa_b', models.CharField(max_length=200)),
                ('alternativa_c', models.CharField(max_length=200)),
                ('alternativa_d', models.CharField(max_length=200)),
                ('alternativaCorreta', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='atividadesprofessor',
            name='perguntas',
            field=models.ManyToManyField(to='cadastros.Perguntasx'),
        ),
        migrations.AddField(
            model_name='atividadesprofessor',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Professor'),
        ),
    ]
