# Generated by Django 2.1.1 on 2018-09-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20180927_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='aluno',
            field=models.OneToOneField(default='Nota não cadastrada', on_delete=django.db.models.deletion.CASCADE, to='cadastros.Aluno'),
            preserve_default=False,
        ),
    ]
