# Generated by Django 2.1.1 on 2018-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_notas_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={},
        ),
        migrations.RemoveField(
            model_name='notas',
            name='media',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='primeiraUnidade',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='segundaUnidade',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='terceiraUnidade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='media',
            field=models.CharField(default='nulo', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='primeiraUnidade',
            field=models.CharField(default='nulo', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='segundaUnidade',
            field=models.CharField(default='nulo', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='terceiraUnidade',
            field=models.CharField(default='nulo', max_length=4),
            preserve_default=False,
        ),
    ]
