# Generated by Django 2.0.7 on 2018-09-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20180927_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
    ]
