# Generated by Django 2.0.7 on 2018-09-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_auto_20180928_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadesprofessor',
            name='teste',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
