# Generated by Django 2.0.7 on 2018-09-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_atividadesprofessor_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadesprofessor',
            name='teste',
        ),
    ]
