# Generated by Django 2.1.1 on 2018-10-04 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_remove_atividadesprofessor_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(choices=[('P', 'Presente'), ('F', 'Faltou')], max_length=1)),
                ('freq1', models.CharField(choices=[('P', 'Presente'), ('F', 'Faltou')], max_length=1)),
                ('freq2', models.CharField(choices=[('P', 'Presente'), ('F', 'Faltou')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Frequência',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('UFPB', 'UFPB'), ('UFCG', 'UFCG'), ('UEPB', 'UEPB')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Instituição',
            },
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='disciplinas',
            options={'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='notas',
            options={'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='frequencia',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='media',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='primeiraUnidade',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='segundaUnidade',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='terceiraUnidade',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='atividadesprofessor',
            name='perguntas',
            field=models.ManyToManyField(related_name='perguntas', to='cadastros.Perguntasx'),
        ),
        migrations.AlterField(
            model_name='atividadesprofessor',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='cadastros.Professor'),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Aluno'),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Professor'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='aluno',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Aluno'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='professor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Professor'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Aluno'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='disciplina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Disciplinas'),
        ),
    ]
