# Generated by Django 2.1.1 on 2018-10-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_auto_20181005_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='frequencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aluno'), to='cadastros.Frequencia'),
        ),
    ]
