# Generated by Django 2.1.1 on 2018-10-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_auto_20181005_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='frequencia',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='disciplina',
            field=models.ManyToManyField(to='cadastros.Disciplinas'),
        ),
    ]
