# Generated by Django 2.1.1 on 2018-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_auto_20181005_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='aluno',
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='aluno',
            field=models.ManyToManyField(blank=True, null=True, to='cadastros.Aluno'),
        ),
    ]
