# Generated by Django 2.1.1 on 2018-10-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_auto_20181005_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='nomeDisciplina',
        ),
    ]
