# Generated by Django 2.1.1 on 2018-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_disciplinas_nomedisciplina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia',
            old_name='freq',
            new_name='freq3',
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='nomeDisciplina',
            field=models.CharField(max_length=30),
        ),
    ]
