# Generated by Django 2.1.1 on 2018-10-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='disciplina',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Disciplinas'),
            preserve_default=False,
        ),
    ]
