# Generated by Django 2.1.1 on 2018-10-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_auto_20181005_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='disciplina',
        ),
    ]
