# Generated by Django 2.1.1 on 2018-10-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_remove_frequencia_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(blank=True, default='a', on_delete=django.db.models.deletion.CASCADE, to='cadastros.Disciplinas'),
            preserve_default=False,
        ),
    ]
