# Generated by Django 2.1.1 on 2018-10-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_frequencia_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Disciplinas'),
        ),
    ]
