# Generated by Django 2.1.1 on 2018-10-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_auto_20181005_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinas',
            name='aluno',
            field=models.ManyToManyField(to='cadastros.Aluno'),
        ),
    ]
