# Generated by Django 2.1.1 on 2018-10-05 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_auto_20181005_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia',
            old_name='aluno',
            new_name='alunosPresentes',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='freq1',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='freq2',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='freq3',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
    ]
