# Generated by Django 2.1.1 on 2018-10-05 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_auto_20181005_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia',
            old_name='alunosPresentes',
            new_name='alunos',
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
