# Generated by Django 2.1.1 on 2018-10-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_auto_20181005_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia',
            old_name='alunos',
            new_name='aluno',
        ),
    ]
