# Generated by Django 2.1.1 on 2018-10-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_auto_20181006_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Aluno'),
            preserve_default=False,
        ),
    ]
