# Generated by Django 2.1.1 on 2018-10-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_auto_20181006_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='frequencia',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Faltou', 'Faltou')], max_length=8),
        ),
    ]
