# Generated by Django 2.1.1 on 2018-10-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_auto_20181006_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='media',
            field=models.CharField(default='Nota não cadastrada', max_length=20),
        ),
    ]
