# Generated by Django 2.1.1 on 2018-10-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_auto_20181006_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Aluno'),
        ),
    ]
