# Generated by Django 2.1.1 on 2018-10-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_auto_20181006_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadesprofessor',
            name='perguntas',
        ),
        migrations.RemoveField(
            model_name='atividadesprofessor',
            name='professor',
        ),
        migrations.AddField(
            model_name='perguntasx',
            name='matricula_professor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perguntasx',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='AtividadesProfessor',
        ),
    ]
