# Generated by Django 2.1.2 on 2018-10-28 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_auto_20181016_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntasx',
            name='alternativaCorreta',
        ),
        migrations.RemoveField(
            model_name='perguntasx',
            name='alternativa_a',
        ),
        migrations.RemoveField(
            model_name='perguntasx',
            name='alternativa_b',
        ),
        migrations.RemoveField(
            model_name='perguntasx',
            name='alternativa_c',
        ),
        migrations.RemoveField(
            model_name='perguntasx',
            name='alternativa_d',
        ),
        migrations.RemoveField(
            model_name='perguntasx',
            name='ask',
        ),
        migrations.AddField(
            model_name='perguntasx',
            name='atividade',
            field=models.FileField(blank=True, upload_to='Documentos/'),
        ),
        migrations.AddField(
            model_name='perguntasx',
            name='data_entrega',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='perguntasx',
            name='instrucoes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perguntasx',
            name='observacoes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='aluno',
            field=models.ManyToManyField(blank=True, to='cadastros.Aluno'),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Professor'),
        ),
    ]
