# Generated by Django 2.1.2 on 2018-10-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_auto_20181028_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntasx',
            name='matricula_professor',
        ),
    ]
