# Generated by Django 2.1.2 on 2018-10-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0046_auto_20181028_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasx',
            name='atividade',
            field=models.FileField(blank=True, upload_to='Documentos/'),
        ),
    ]
