# Generated by Django 2.1.2 on 2018-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0047_auto_20181028_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntasx',
            name='matricula_professor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
